### PR TITLE
get gps data code

### PR DESCRIPTION
**Pull request by toomb1r**
I created a function within main that gets GPS location at the time of request and returns csv file path

### CODE REVIEW

**Review by ReginPotter — COMMENTED** [review]
This may not be correct since we have changed the GPS unit, although Billy might have been able to order the correct GPS unit. We can discuss further on Tuesday.

**Comment by ReginPotter** [comment]
> This may not be correct since we have changed the GPS unit, although Billy might have been able to order the correct GPS unit. We can discuss further on Tuesday.

After some discussion this doesn't matter 👍

**Review by ReginPotter — APPROVED** [review]
Looks good for now, I am unable to test this so testing later on will be very important. Although for now in the interest of continuing things on I will approve this.

**Review by L30N1DAS — CHANGES_REQUESTED** [review]
Code is not fully PEP 8 compliant. Add documentation strings: [PEP 8 Guide on Comment](shttps://peps.python.org/pep-0008/#documentation-strings:~:text=Use%20Trailing%20Commas-,Comments,-Block%20Comments).

Adding block or inline comments is suggested for code that is more difficult to understand. I will leave the necessity of these for you to decide upon.

**Review by ReginPotter — CHANGES_REQUESTED** [review]
Please put your code above the `main` method and call your method in the `main` method and then that should be all fine unless Anmol says otherwise

**Comment by ReginPotter** [comment]
Tiff im so sorry 😂 please remove lines 64 and 65 im just gonna comment this :)

**Comment by ReginPotter** [comment]
Looks fine to me now but I am not approving this until Anmol checks because I made a mistake earlier in this PR with the docstrings

**Review by L30N1DAS — CHANGES_REQUESTED** [review]
Should be visible?

**Review by ReginPotter — CHANGES_REQUESTED** [review]
In every file please make sure there is one line of whitespace at the end of the file, `main.py` for the Controller does this but the other two files have two or more blank lines.

Also please put the GPS.py file in the utils folder (this will be visible once you merge dev). Also I dont know if PEP8 has any standards for file names, but just in case please consult Anmol about that.

# Changes requested: 
- [ ] Merge `dev` branch into `GPS3` branch
- [ ] Remove excess whitespace lines at the end of every file
- [ ] Put the `GPS.py` file in the correct location
- [ ] Consult Anmol about PEP8 compliance

**Pull request closed without merging**
