### PR TITLE
Preliminary movement code

### PR DESCRIPTION
**Pull request by ReginPotter**
# Movement PR

## What this PR includes
This PR includes edge detection and movement.
This PR includes an attempt at the turning code although it is wrong for now.

## Basic idea
- PEAT will randomly pick a direction from -90 to 90 degrees in front of it, where 0 degrees is straight forward.
- Once this random direction is chosen it will move to look that way and move forward.
- It will move forward until it detects the edge of the pond.
- Once it detects the edge of the pond it will turn one direction and move a little forward.
- Once it moves forward it then turns back towards the opposite edge of the pond and move there.
- This will continue until it hits the final edge of the pond.

## Ways to test
No way to test until the Raspberry Pi is set up

## Future work
I will need to change the turning code to actually work.
I may change how the movement actually works since this might not be the best way to do it.

## What I am asking
- I would like if any reviewers could provide a different perspective on whether this is a good option or if there is another better way.
- I believe a discussion about how our "main function" will work on Tuesday is necessary

### CODE REVIEW

**Comment by toomb1r** [comment]
Did some googling about roombas and their movement.
Ran into this article: https://www.cnet.com/home/kitchen-and-household/this-is-why-your-roombas-random-patterns-actually-make-perfect-sense/
Then the article referenced this term. VSLAM: https://www.mathworks.com/help/vision/visual-simultaneous-localization-and-mapping-slam.html
Seems like a method that would be relevant to what we need! Though it does not work well in the dark. 

I wonder how feasible it is to code this in. Otherwise, I think the random function you have is good. However, it may lead to our robot circling one area too much.
image

**Comment by ReginPotter** [comment]
I have made changes to the Move code and it is now more filled out. I think this code is good enough to be merged although none of it is tested since it relies heavily on the GPIO pins and that library can only be installed on the Raspberry Pi. I also will need to actually wire things up to test this which can be done on Tuesday or Wednesday of next week.

**Review by L30N1DAS — CHANGES_REQUESTED** [review]
Code is not fully PEP 8 compliant. Add documentation strings: [PEP 8 Guide on Comments](https://peps.python.org/pep-0008/#documentation-strings:~:text=Use%20Trailing%20Commas-,Comments,-Block%20Comments).

**Comment by ReginPotter** [comment]
> Code is not fully PEP 8 compliant. Add documentation strings: [PEP 8 Guide on Comments](https://peps.python.org/pep-0008/#documentation-strings:~:text=Use%20Trailing%20Commas-,Comments,-Block%20Comments).

I have made the requested changes, please review again.

**Review by L30N1DAS — APPROVED** [review]
Looks good, needs to be tested when the PI is set up

**Pull request merged**
