### PR TITLE
Emergency Stop command

### PR DESCRIPTION
**Pull request by ReginPotter**
Issue will be created to set up interrupts for this GPIO pin

# Description

This change will create the emergency stop code for the Emergency Stop button. If the Emergency Stop button is pressed it will send an encrypted signal to PEAT to force it to cease all functions.

Fixes no existing issue

# Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

### Unfortunately at this moment we are unable to test this function as it uses RPi.GPIO. This means it can be only tested on a Raspberry Pi.

- [x] Test A
    - Place a print statement inside the `emergencyStop` command printing out `signal`
    - Run the code
      - This should encrypt the signal and send it to PEAT
    - The output should be the string `stop` 

**Test Configuration**:
* Firmware version:
* Hardware: Raspberry Pi
* Toolchain:
* SDK:

# Checklist:

- [X] My code follows the style guidelines of this project (Pep 8)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (if applicable)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ReginPotter** [comment]
This might work better, it is now blocking stuff waiting for the button to be pressed again. This will need to be workshopped though.

**Comment by ReginPotter** [comment]
> Reference in

This actually wont work. I am changing it to now just be super simple and this should work. Testing will be completed on 3/26.

**Comment by ReginPotter** [comment]
> This might work better, it is now blocking stuff waiting for the button to be pressed again. This will need to be workshopped though.
This actually wont work. Changed functionality to be much easier and should work. Testing will be done on 3/26.

**Review by L30N1DAS — APPROVED** [review]
Works, adds new feature of turning on other functions if they were off

**Comment by ReginPotter** [comment]
WRONG ONE THIS BORKED

**Pull request closed without merging**
